pika:
  - addr: 127.0.0.1:9221
    db: 0
    password: ""

  - addr: 127.0.0.1:9221
    db: 1
    password: ""

  - addr: 127.0.0.1:9221
    db: 2
    password: ""

scan-size: 1000 # scan size per time
concurrency: 1000 # goroutine num
head: 20 # show top head keys
type:
  - string
  - hash
  - list
  - set
  - zset
memory: 2000 # Memory limit, unit: MB
print: true # Print key number or not, will use keys command
