apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kb-{{ include "clustername" . }}
  labels:
    {{ include "redis-cluster.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kb-{{ include "clustername" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "redis-cluster.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
