apiVersion: v2
name: pika-cluster
description: A Pika Codis Cluster Helm chart for KubeBlocks.

type: application

version: 0.6.0-alpha.21

appVersion: "3.5.0"

home: https://github.com/OpenAtomFoundation/pika
keywords:
  - pika
  - redis
  - database
  - nosql
  - replication
  - codis

maintainers:
  - name: pika
    url: https://github.com/OpenAtomFoundation/pika/tools/kubeblocks_helm
