name: Bug Report
description: Report a bug in the PikiwiDB
labels: [ "☢️ Bug" ]

body:
  - type: dropdown
    id: is-regression
    attributes:
      label: Is this a regression?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: input
    id: reproduction
    attributes:
      label: Please provide a link to a minimal reproduction of the bug

  - type: textarea
    attributes:
      label: Screenshots or videos
      description: If you can, upload any screenshots of the bug.

  - type: textarea
    id: environment
    attributes:
      label: Please provide the version you discovered this bug in (check about page for version information)
      render: true
      placeholder: |
        Version: v0.0.1
        Commit Hash: 7c9b67171b4d2fbdd37218e59dbabe64451d9d68
        Build Date: Oct 11, 2023, 10:49 AM GMT+8
        OS: linux x64

  - type: textarea
    id: other
    attributes:
      label: Anything else?
