FROM golang:1.20 AS builder

LABEL maintainer="pikiwidb@gmail.com"

ENV PIKA=/pika \
    PIKA_BUILD_DIR=/tmp/pika \
    PIKA_CODIS_BUILD_DIR=/tmp/pika/codis \
    PATH=${PIKA}:${PIKA}/bin:${PATH}

ARG ENABLE_PROXY=false
RUN if [ "${ENABLE_PROXY}" = "true" ] ; \
    then go env -w GOPROXY=https://goproxy.io,direct; \
    fi

COPY . ${PIKA_BUILD_DIR}

WORKDIR ${PIKA_CODIS_BUILD_DIR}

RUN go env && make

FROM ubuntu:22.04

LABEL maintainer="pikiwidb@gmail.com"

ENV PIKA=/pika \
    PIKA_BUILD_DIR=/tmp/pika \
    PATH=${PIKA}:${PIKA}/bin:${PATH}

WORKDIR ${PIKA}

COPY --from=builder ${PIKA_BUILD_DIR}/codis/admin ${PIKA}/bin/admin
COPY --from=builder ${PIKA_BUILD_DIR}/codis/config ${PIKA}/bin/config
COPY --from=builder ${PIKA_BUILD_DIR}/codis/bin ${PIKA}/bin/bin

EXPOSE 9121

CMD ["/pika/bin/pika_codis", "--config", "/pika/conf/info.toml"]

