FROM ubuntu:22.04

RUN  sed -i 's/http:\/\/archive.ubuntu.com/http:\/\/mirrors.aliyun.com/g' /etc/apt/sources.list ; \
     sed -i 's/http:\/\/ports.ubuntu.com/http:\/\/mirrors.aliyun.com/g' /etc/apt/sources.list ; \
     sed -i 's/http:\/\/security.ubuntu.com/http:\/\/mirrors.aliyun.com/g' /etc/apt/sources.list 

RUN apt-get update && apt-get install -y \
    ca-certificates \
    rsync && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives
