apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterDefinition
metadata:
  name: pika
  labels:
    {{- include "pika.labels" . | nindent 4 }}
spec:
  topologies: 
  - name: replication-codis
    components:
    - name: pika-group
      compDef: componentdefinition-pika-group
    - name: etcd
      compDef: componentdefinition-etcd
    - name: pika-exporter
      compDef: componentdefinition-pika-exporter
    - name: codis-proxy
      compDef: componentdefinition-codis-proxy
    - name: codis-fe
      compDef: componentdefinition-codis-fe
    - name: codis-dashboard
      compDef: componentdefinition-codis-dashboard
    default: true
