apiVersion: apps.kubeblocks.io/v1alpha1
kind: ComponentVersion
metadata:
  name: pika-etcd
  labels:
    {{- include "pika.labels" . | nindent 4 }}
spec:
  compatibilityRules:
    - compDefs: 
      - pika-etcd
      releases: 
        - {{ .Chart.AppVersion }}
  releases:
    - name: {{ .Chart.AppVersion }}
      changes:
      serviceVersion: {{ .Chart.AppVersion }}
      images:
        pika-etcd: {{ include "etcd.image" . }}