apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterDefinition
metadata:
  name: pika
  labels:
    {{- include "pika.labels" . | nindent 4 }}
spec:
  topologies:
    - name: master-slave-cluster
      components:
        - name: master-slave
          compDef: pika
      default: true