apiVersion: apps.kubeblocks.io/v1alpha1
kind: ComponentVersion
metadata:
  name: pika-exporter
  labels:
    {{- include "pika.labels" . | nindent 4 }}
spec:
  compatibilityRules:
    - compDefs:
        - pika-exporter
      releases:
        - {{ .Chart.AppVersion }}
  releases:
    - name: {{ .Chart.AppVersion }}
      changes:
      serviceVersion: {{ .Chart.AppVersion }}
      images:
        codis-dashboard: {{ include "pikaExporter.image" . }}