apiVersion: apps.kubeblocks.io/v1alpha1
kind: ComponentDefinition
metadata:
  name: redis-sentinel
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pika.labels" . | nindent 4 }}
spec:
  clusterSize: 3
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
  redisSentinelConfig:
    redisReplicationName: redis-replication
  kubernetesConfig:
    image: 'quay.io/opstree/redis-sentinel:v7.0.7'
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 101m
        memory: 128Mi
      limits:
        cpu: 101m
        memory: 128Mi
  updateStrategy: Serial
  configs:
    - name: pika-config
      templateRef: pika-conf-template
      namespace: {{ .Release.Namespace }}
      volumeName: config
 containers:
      - name: redis-sentinel
        image: {{ include "pikaExporter.image" . }}
        imagePullPolicy: {{ include "pikaExporter.imagePullPolicy" . }}
        ports:
          - name: expoter
            containerPort: 9121
        volumeMounts:
          - name: config
            mountPath: /etc/pika
        env:
          - name: DASHBOARD_ADDR
            value: "$(KB_CLUSTER_NAME)-codis-dashboard"
        command:
          - "/pika/bin/pika_exporter"
        args:
          - "-config"
          - "/etc/pika/info.toml"
          - "-codis.addr"
          - "http://$(DASHBOARD_ADDR):18080/topom"