apiVersion: apps.kubeblocks.io/v1alpha1
kind: ComponentDefinition
metadata:
  name: pika
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pika.labels" . | nindent 4 }}
spec:
  provider: pika
  description: Pika component definition
  serviceKind: pika
  serviceVersion: {{ .Chart.AppVersion }}
  services:
    - name: pika
      spec:
        ports:
          - name: pika
            port: 9221
            targetPort: pika
  updateStrategy: Serial
  configs:
    - name: config
      templateRef: pika-master-slave-conf-template
      namespace: {{ .Release.Namespace }}
      volumeName: config
  scripts:
    - name: script
      templateRef: pika-master-slave-script-template
      namespace: {{ .Release.Namespace }}
      volumeName: script
      defaultMode: 0555
  volumes:
    - name: data
  lifecycleActions:
    memberJoin:
      customHandler:
        image: {{ include "redis.image" . }}
        exec:
          command:
           - /bin/sh
           - -c
           - "redis-cli -h ${CURRENT_POD_IP} -p ${KB_SERVICE_PORT} slaveof $(KB_MEMBER_ADDRESSES%%,*)"
        preCondition: RuntimeReady
  runtime:
    initContainers:
      - name: init-config
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -ec
          - |
            if [ ! -f "/data/pika.conf" ];then cp /etc/pika/pika.conf /data/pika.conf; fi
        volumeMounts:
          - name: config
            mountPath: /etc/pika
          - name: data
            mountPath: /data  
    containers:
      - name: pika
        image: {{ include "pika.image" . }}
        imagePullPolicy: {{ include "pika.imagePullPolicy" . }}
        ports:
          - name: pika
            containerPort: 9221
        volumeMounts:
          - name: config
            mountPath: /etc/pika
          - name: data
            mountPath: /data
          - name: script
            mountPath: /script
        env:
          - name: CURRENT_POD_HOST_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
        command:
          - "/pika/bin/pika"
        args:
          - "-c"
          - "/etc/pika/pika.conf"