apiVersion: v1
kind: ConfigMap
metadata:
  name: pika-master-slave-script-template
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pika.labels" . | nindent 4 }}
data:
  admin.sh: |-
    {{- .Files.Get "script/admin.sh" | nindent 4 }}