apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pika-cluster.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "pika-cluster.labels" . | nindent 4 }}
