{
 "title": "Prometheus Pika Exporter",
 "tags": [
  "prometheus",
  "pika"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(pika_server_info, job)"
   },
   {
    "name": "group",
    "label": "Group",
    "query": "label_values(pika_server_info{job=~'$job'},group)"
   },
   {
    "name": "instance",
    "label": "Collect Instance",
    "query": "label_values(pika_server_info{job=~\"$job\", group=~'$group'}, instance)"
   },
   {
    "name": "addr",
    "label": "Pika Server Addr",
    "query": "label_values(pika_server_info{job=~\"$job\", group=~'$group'}, addr)"
   },
   {
    "name": "alias",
    "label": "Pika Server Alias",
    "query": "label_values(pika_server_info{job=~\"$job\", group=~'$group', addr=~'$addr'}, alias)"
   },
   {
    "name": "role",
    "label": "Role",
    "query": "label_values(pika_server_info{job=~\"$job\", group=~'$group', addr=~'$addr'}, role)"
   },
   {
    "name": "serverid",
    "label": "Server ID",
    "query": "label_values(pika_server_info{job=~\"$job\", group=~'$group', addr=~'$addr'}, server_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Pika Build Info List",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "pika_build_info{job=~\"$job\", group=~\"$group\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Pika Server Info List",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "pika_server_info{job=~\"$job\", group=~\"$group\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Base Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Build Info",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "pika_build_info{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
    }
   ]
  },
  {
   "title": "Server Info",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "pika_server_info{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
    }
   ]
  },
  { "title": "Server ID", "type": "vonage-status-panel", "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 } },
  { "title": "Role", "type": "vonage-status-panel", "gridPos": { "h": 4, "w": 4, "x": 3, "y": 8 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pika_uptime_in_seconds{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
    }
   ]
  },
  {
   "title": "Tread Num",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pika_thread_num{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
    }
   ]
  },
  {
   "title": "Sync Thread Num",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pika_sync_thread_num{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
    }
   ]
  },
  {
   "title": "Total Connections Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pika_total_connections_received{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
    }
   ]
  },
  {
   "title": "Total Commands Processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pika_total_commands_processed{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pika_connected_clients{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "connected-clients"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(irate(pika_used_cpu_sys{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}[1m]) + irate(pika_used_cpu_user{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}[1m])) * 100",
     "legendFormat": "cpu-usage"
    }
   ]
  },
  {
   "title": "CPU Usage Children",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(irate(pika_used_cpu_sys_children{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}[1m]) + irate(pika_used_cpu_user_children{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}[1m])) * 100",
     "legendFormat": "cpu-usage-children"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pika_used_memory{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "used-memory"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pika_db_size{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "compression-{{compression}}"
    }
   ]
  },
  {
   "title": "DB Memtable Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pika_db_memtable_usage{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "db-memtable-usage"
    },
    {
     "expr": "pika_db_tablereader_usage{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "db-tablereader-usage"
    }
   ]
  },
  {
   "title": "Commands Processed in per second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pika_total_commands_processed{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}[5m])",
     "legendFormat": "commands-processed/sec"
    }
   ]
  },
  {
   "title": "The number of Keys",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pika_kv_keys{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "kv-keys"
    },
    {
     "expr": "pika_hash_keys{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "hash-keys"
    },
    {
     "expr": "pika_list_keys{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "list-keys"
    },
    {
     "expr": "pika_set_keys{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "set-keys"
    },
    {
     "expr": "pika_zset_keys{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "zset-keys"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Master Link Status",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pika_master_link_status{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{master_host}} {{master_port}}"
    }
   ]
  },
  {
   "title": "Slave Priority",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pika_slave_priority{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{master_host}} {{master_port}}"
    }
   ]
  },
  { "title": "Role", "type": "vonage-status-panel", "gridPos": { "h": 5, "w": 4, "x": 0, "y": 51 } },
  {
   "title": "Connected Slaves",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pika_master_info{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "connected-slaves"
    }
   ]
  },
  {
   "title": "Connected Slave List",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "pika_master_slave_info{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
    }
   ]
  },
  {
   "title": "Binlog Setting",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "pika_binlog{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
    }
   ]
  },
  {
   "title": "Binlog Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pika_binlog{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "binlog size"
    }
   ]
  },
  {
   "title": "Binlog Offset",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pika_binlog_offset{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "file-num: [{{binlog_offset_filenum}}]  binlog-offset"
    }
   ]
  },
  {
   "title": "Double Master Info",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "pika_double_master_info{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
    }
   ]
  },
  {
   "title": "Double Master Binlog Offset",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pika_double_master_recv_info{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "filenum:[{{double_master_recv_info_binlog_filenum}}]   binlog-offset"
    }
   ]
  },
  {
   "title": "Time-consuming operation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Scan Keyspace",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "pika_is_scaning_keyspace{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
    }
   ]
  },
  {
   "title": "Bgsave",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "pika_is_bgsaving{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
    }
   ]
  },
  {
   "title": "Slots Clean",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "pika_is_slots_cleaning{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
    }
   ]
  },
  {
   "title": "Slots Reload",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "expr": "pika_is_slots_reloading{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
    }
   ]
  },
  {
   "title": "Compact",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "pika_is_compact{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
    }
   ]
  },
  {
   "title": "Keys Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Keys",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pika_keys{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}} {{db}} "
    }
   ]
  },
  {
   "title": "Expire Keys",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 83 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pika_expire_keys{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}} {{db}} "
    }
   ]
  },
  {
   "title": "Invalid Keys",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 83 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pika_invalid_keys{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}} {{db}} "
    }
   ]
  },
  { "title": "RocksDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Is Memtable Flush Pending",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pika_mem_table_flush_pending{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Num Immutable MemTable",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pika_num_immutable_mem_table{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Num Immutable Memtable Flushed",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pika_num_immutable_mem_table_flushed{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Num Running Flushes",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pika_num_running_flushes{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Cur Size Active Memtable",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pika_cur_size_active_mem_table{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Cur Size All Memtables",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 108 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pika_cur_size_all_mem_tables{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Size All Memtables",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 108 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pika_size_all_mem_tables{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Block Cache Capacity",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pika_block_cache_capacity{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Block Cache Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 121 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pika_block_cache_usage{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Block Cache Pinned Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 121 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pika_block_cache_pinned_usage{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Is Compaction Pending",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pika_compaction_pending{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Running Compactions",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 134 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pika_num_running_compactions{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Total SST Files Size",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 134 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pika_total_sst_files_size{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Live SST Files Size",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 134 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pika_live_sst_files_size{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Num Blob Files",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 147 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pika_num_blob_files{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Blob Stats",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 147 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pika_blob_stats{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Total Blob File Size",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 147 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pika_total_blob_file_size{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Live Blob File Size",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 147 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pika_live_blob_file_size{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Estimate Live Data Size",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pika_estimate_live_data_size{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Estimate Table Readers Mem",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 160 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pika_estimate_table_readers_mem{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Estimate Num Keys",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 160 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pika_estimate_num_keys{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Num Background Errors",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 173 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pika_background_errors{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Current Super Version Number",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 173 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pika_current_super_version_number{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Live Versions",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 173 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pika_num_live_versions{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 173 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pika_num_snapshots{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
     "legendFormat": "{{data_type}}"
    }
   ]
  }
 ]
}