apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: {{ include "clustername" . }}
  labels: {{ include "pika-cluster.labels" . | nindent 4 }}
spec:
  clusterDefinitionRef: pika  # ref clusterDefinition.name
  clusterVersionRef: pika-{{ default .Chart.AppVersion .Values.clusterVersionOverride }} # ref clusterVersion.name
  terminationPolicy: {{ .Values.terminationPolicy }}
  affinity:
    {{- with .Values.topologyKeys }}
    topologyKeys: {{ . | toYaml | nindent 6 }}
    {{- end }}
  {{- with $.Values.tolerations }}
  tolerations: {{ . | toYaml | nindent 4 }}
  {{- end }}
  componentSpecs:
    {{- range $i := until (int .Values.replicaCount) }}
    - name: pika-group-{{ add ($i) 1 }} # user-defined
      componentDefRef: pika-group # ref clusterDefinition componentDefs.name
      monitor: {{ $.Values.monitor.enabled | default false }}
      enabledLogs: {{ $.Values.enabledLogs | toJson | indent 4 }}
      replicas: {{ add (int $.Values.slaveCount) 1 | default 2 }}
      serviceAccountName: {{ include "pika-cluster.serviceAccountName" $ }}
      switchPolicy:
        type: {{ $.Values.switchPolicy.type}}
      {{- with  $.Values.resources }}
      resources:
        limits:
          cpu: {{ .limits.cpu | quote }}
          memory: {{ .limits.memory | quote }}
        requests:
          cpu: {{ .requests.cpu | quote }}
          memory: {{ .requests.memory | quote }}
      {{- end }}
      {{- if $.Values.persistence.enabled }}
      volumeClaimTemplates:
        - name: data # ref clusterdefinition components.containers.volumeMounts.name
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ $.Values.persistence.data.size }}
      {{- end }}
    {{- end }}
    - name: etcd # user-defined
      componentDefRef: etcd # ref clusterdefinition components.name
      monitor: {{ .Values.monitor.enabled | default false }}
      replicas: {{ .Values.etcdReplicaCount| default 3 }}
      {{- with  .Values.resources }}
      resources:
        {{- with .limits }}
        limits:
          cpu: {{ .cpu | quote }}
          memory: {{ .memory | quote }}
        {{- end }}
        {{- with .requests }}
        requests:
          cpu: {{ .cpu | quote }}
          memory: {{ .memory | quote }}
        {{- end }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      volumeClaimTemplates:
        - name: data # ref clusterdefinition components.containers.volumeMounts.name
          spec:
            storageClassName: {{ .Values.persistence.data.storageClassName }}
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ .Values.persistence.data.size }}
      {{- end }}
    - name: codis-proxy
      componentDefRef: codis-proxy # ref clusterDefinition componentDefs.name
      replicas: {{ .Values.codisProxyReplicaCount | default 2 }}
      {{- with  .Values.resources }}
      resources:
        limits:
          cpu: {{ .limits.cpu | quote }}
          memory: {{ .limits.memory | quote }}
        requests:
          cpu: {{ .requests.cpu | quote }}
          memory: {{ .requests.memory | quote }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      volumeClaimTemplates:
        - name: data # ref clusterdefinition components.containers.volumeMounts.name
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ .Values.persistence.data.size }}
      {{- end }}
    - name: codis-fe
      componentDefRef: codis-fe # ref clusterDefinition componentDefs.name
      replicas: {{ .Values.codisFeReplicaCount | default 1 }}
      {{- with  .Values.resources }}
      resources:
        limits:
          cpu: {{ .limits.cpu | quote }}
          memory: {{ .limits.memory | quote }}
        requests:
          cpu: {{ .requests.cpu | quote }}
          memory: {{ .requests.memory | quote }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      volumeClaimTemplates:
        - name: data # ref clusterdefinition components.containers.volumeMounts.name
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ .Values.persistence.data.size }}
      {{- end }}
    - name: codis-dashboard
      componentDefRef: codis-dashboard # ref clusterDefinition componentDefs.name
      replicas: 1
    {{- with  .Values.resources }}
      resources:
        limits:
          cpu: {{ .limits.cpu | quote }}
          memory: {{ .limits.memory | quote }}
        requests:
          cpu: {{ .requests.cpu | quote }}
          memory: {{ .requests.memory | quote }}
    {{- end }}
    {{- if .Values.persistence.enabled }}
      volumeClaimTemplates:
        - name: data # ref clusterdefinition components.containers.volumeMounts.name
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ .Values.persistence.data.size }}
    {{- end }}
