apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: {{ include "clustername" . }}
  labels: {{ include "pika-cluster.labels" . | nindent 4 }}
spec:
  clusterDefinitionRef: pika  # ref clusterDefinition.name
  clusterVersionRef: pika-{{ default .Chart.AppVersion .Values.clusterVersionOverride }} # ref clusterVersion.name
  terminationPolicy: {{ .Values.terminationPolicy }}
  affinity:
    {{- with .Values.topologyKeys }}
    topologyKeys: {{ . | toYaml | nindent 6 }}
    {{- end }}
  {{- with $.Values.tolerations }}
  tolerations: {{ . | toYaml | nindent 4 }}
  {{- end }}
  {{- if not .Values.useLegacyCompDef }}
  shardingSpecs:
  {{- include "pika-group.shardingSpec" . | indent 6 }}
  {{- end }}
  componentSpecs:
    {{- if not .Values.useLegacyCompDef }}
    {{- range $i := until (int .Values.replicaCount) }}
    - name: pika-group-{{ add ($i) 1 }} # user-defined
      componentDefRef: pika-group # ref clusterDefinition componentDefs.name
      monitor: {{ $.Values.monitor.enabled | default false }}
      enabledLogs: {{ $.Values.enabledLogs | toJson | indent 4 }}
      replicas: {{ add (int $.Values.slaveCount) 1 | default 2 }}
      serviceAccountName: {{ include "pika-cluster.serviceAccountName" $ }}
      switchPolicy:
        type: {{ $.Values.switchPolicy.type}}
      {{- with  $.Values.resources.pikaGroup }}
      resources:
        limits:
          cpu: {{ .limits.cpu | quote }}
          memory: {{ .limits.memory | quote }}
        requests:
          cpu: {{ .requests.cpu | quote }}
          memory: {{ .requests.memory | quote }}
      {{- end }}
      {{- if $.Values.persistence.enabled }}
      volumeClaimTemplates:
        {{- with  $.Values.persistence.pikaData }}
        - name: data # ref clusterdefinition components.containers.volumeMounts.name
          spec:
            storageClassName: {{ .storageClassName }}
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ .size }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
    - name: etcd # user-defined
      {{- if .Values.useLegacyCompDef }}
      componentDefRef: etcd # ref clusterDefinition.componentDefs[x].name
      {{- else }}
      componentDef: pika-etcd # ref componentDefinition name
      {{- end }}
      monitor: {{ .Values.monitor.enabled | default false }}
      replicas: {{ .Values.etcdReplicaCount| default 3 }}
      {{- with  .Values.resources.etcd }}
      resources:
        {{- with .limits }}
        limits:
          cpu: {{ .cpu | quote }}
          memory: {{ .memory | quote }}
        {{- end }}
        {{- with .requests }}
        requests:
          cpu: {{ .cpu | quote }}
          memory: {{ .memory | quote }}
        {{- end }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      volumeClaimTemplates:
        {{- with  $.Values.persistence.pikaData }}
        - name: data # ref clusterdefinition components.containers.volumeMounts.name
          spec:
            storageClassName: {{ .storageClassName }}
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ .size }}
        {{- end }}
      {{- end }}
    - name: codis-proxy
      {{- if .Values.useLegacyCompDef }}
      componentDefRef: codis-proxy # ref clusterDefinition.componentDefs[x].name
      {{- else }}
      componentDef: pika-codis-proxy # ref componentDefinition name
      {{- end }}
      replicas: {{ .Values.codisProxyReplicaCount | default 2 }}
      {{- with  .Values.resources.codisProxy }}
      resources:
        limits:
          cpu: {{ .limits.cpu | quote }}
          memory: {{ .limits.memory | quote }}
        requests:
          cpu: {{ .requests.cpu | quote }}
          memory: {{ .requests.memory | quote }}
      {{- end }}
    - name: codis-fe
      {{- if .Values.useLegacyCompDef }}
      componentDefRef: codis-fe # ref clusterDefinition.componentDefs[x].name
      {{- else }}
      componentDef: pika-codis-fe # ref componentDefinition name
      {{- end }}
      replicas: {{ .Values.codisFeReplicaCount | default 1 }}
      {{- with  .Values.resources.codisFe }}
      resources:
        limits:
          cpu: {{ .limits.cpu | quote }}
          memory: {{ .limits.memory | quote }}
        requests:
          cpu: {{ .requests.cpu | quote }}
          memory: {{ .requests.memory | quote }}
      {{- end }}
    - name: codis-dashboard
      {{- if .Values.useLegacyCompDef }}
      componentDefRef: codis-dashboard # ref clusterDefinition.componentDefs[x].name
      {{- else }}
      componentDef: pika-codis-dashboard # ref componentDefinition name
      {{- end }}
      replicas: 1
    {{- with  .Values.resources.codisFe }}
      resources:
        limits:
          cpu: {{ .limits.cpu | quote }}
          memory: {{ .limits.memory | quote }}
        requests:
          cpu: {{ .requests.cpu | quote }}
          memory: {{ .requests.memory | quote }}
    {{- end }}
