apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: {{ include "clustername" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "pika-cluster.labels" . | nindent 4 }}
spec:
  clusterDefinitionRef: pika  # ref clusterDefinition.name
  topology: replication-codis
  terminationPolicy: {{ .Values.terminationPolicy }}
  affinity:
    {{- with .Values.topologyKeys }}
    topologyKeys: {{ . | toYaml | nindent 6 }}
    {{- end }}
  {{- with $.Values.tolerations }}
  tolerations: {{ . | toYaml | nindent 4 }}
  {{- end }}
  ## define pika group with shardingSpecs API which is supported in KubeBlocks v0.8.2
  shardingSpecs:
  - name: group
    shards: {{ .Values.groupCount }}
    template:
      name: pika
      componentDef: pika-group
      enabledLogs: {{ $.Values.enabledLogs | toJson | indent 4 }}
      serviceAccountName: {{ include "pika-cluster.serviceAccountName" $ }}
      replicas: {{ add (int $.Values.slaveCount) 1 | default 2 }}
      {{- with  $.Values.resources.pikaGroup }}
      resources:
        limits:
          cpu: {{ .limits.cpu | quote }}
          memory: {{ .limits.memory | quote }}
        requests:
          cpu: {{ .requests.cpu | quote }}
          memory: {{ .requests.memory | quote }}
      {{- end }}
      {{- if $.Values.persistence.enabled }}
      volumeClaimTemplates:
        {{- with  $.Values.persistence.pikaData }}
        - name: data
          spec:
            storageClassName: {{ .storageClassName }}
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ .size }}
        {{- end }}
      {{- end }}
  componentSpecs:
    - name: pika-group # user-defined
      componentDef: pika-group # ref clusterDefinition.componentDefs[x].name
      monitor: {{ $.Values.monitor.enabled | default false }}
      enabledLogs: {{ $.Values.enabledLogs | toJson | indent 4 }}
      replicas: {{ add (int $.Values.slaveCount) 1 | default 2 }}
      serviceAccountName: {{ include "pika-cluster.serviceAccountName" $ }}
      switchPolicy:
        type: {{ $.Values.switchPolicy.type}}
      {{- with  $.Values.resources.pikaGroup }}
      resources:
        limits:
          cpu: {{ .limits.cpu | quote }}
          memory: {{ .limits.memory | quote }}
        requests:
          cpu: {{ .requests.cpu | quote }}
          memory: {{ .requests.memory | quote }}
      {{- end }}
      {{- if $.Values.persistence.enabled }}
      volumeClaimTemplates:
        {{- with  $.Values.persistence.pikaData }}
        - name: data # ref clusterdefinition components.containers.volumeMounts.name
          spec:
            storageClassName: {{ .storageClassName }}
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ .size }}
        {{- end }}
      {{- end }}
    - name: etcd # user-defined
      componentDef: pika-etcd # ref componentDefinition name
      #monitor: {{ .Values.monitor.enabled | default false }}
      replicas: {{ .Values.etcdReplicaCount| default 3 }}
      {{- with  .Values.resources.etcd }}
      resources:
        {{- with .limits }}
        limits:
          cpu: {{ .cpu | quote }}
          memory: {{ .memory | quote }}
        {{- end }}
        {{- with .requests }}
        requests:
          cpu: {{ .cpu | quote }}
          memory: {{ .memory | quote }}
        {{- end }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      volumeClaimTemplates:
        {{- with  $.Values.persistence.etcdData }}
        - name: data # ref clusterdefinition components.containers.volumeMounts.name
          spec:
            storageClassName: {{ .storageClassName }}
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ .size }}
        {{- end }}
      {{- end }}
    - name: codis-proxy
      componentDef: pika-codis-proxy # ref componentDefinition name
      replicas: {{ .Values.codisProxyReplicaCount | default 2 }}
      {{- with  .Values.resources.codisProxy }}
      resources:
        limits:
          cpu: {{ .limits.cpu | quote }}
          memory: {{ .limits.memory | quote }}
        requests:
          cpu: {{ .requests.cpu | quote }}
          memory: {{ .requests.memory | quote }}
      {{- end }}
    - name: codis-fe
      componentDef: pika-codis-fe # ref componentDefinition name
      replicas: {{ .Values.codisFeReplicaCount | default 1 }}
      {{- with  .Values.resources.codisFe }}
      resources:
        limits:
          cpu: {{ .limits.cpu | quote }}
          memory: {{ .limits.memory | quote }}
        requests:
          cpu: {{ .requests.cpu | quote }}
          memory: {{ .requests.memory | quote }}
      {{- end }}
    - name: codis-dashboard
      componentDef: pika-codis-dashboard # ref componentDefinition name
      replicas: 1
    {{- with  .Values.resources.codisFe }}
      resources:
        limits:
          cpu: {{ .limits.cpu | quote }}
          memory: {{ .limits.memory | quote }}
        requests:
          cpu: {{ .requests.cpu | quote }}
          memory: {{ .requests.memory | quote }}
    {{- end }}
