apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kb-{{ include "clustername" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "pika-cluster.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
