apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterDefinition
metadata:
  name: pika
  labels:
    {{- include "pika.labels" . | nindent 4 }}
spec:
  type: pika
  connectionCredential:
    username: default
    password: "$(RANDOM_PASSWD)"
    endpoint: "$(SVC_FQDN):$(SVC_PORT_pika)"
    host: "$(SVC_FQDN)"
    port: "$(SVC_PORT_pika)"
  componentDefs:
    - name: pika
      workloadType: Replication
      characterType: pika
      service:
        ports:
          - name: pika
            port: 9221
            targetPort: pika
      configSpecs:
        - name: pika-config
          templateRef: pika-conf-template
          namespace: {{ .Release.Namespace }}
          volumeName: config
      volumeTypes:
        - name: data
          type: data
      podSpec:
        containers:
          - name: pika
            ports:
              - name: pika
                containerPort: 9221
            volumeMounts:
              - name: data
                mountPath: /data
              - name: config
                mountPath: /etc/pika
            command:
              - "/pika/bin/pika"
            args:
              - "-c"
              - "/etc/pika/pika.conf"
    - name: redis-sentinel
      workloadType: Stateful
      characterType: redis
      service:
        ports:
          - name: redis-sentinel
            targetPort: redis-sentinel
            port: 26379
      configSpecs:
        - name: codis-sentinel-config
          templateRef: pika-conf-template
          namespace: {{ .Release.Namespace }}
          volumeName: config
      volumeTypes:
        - name: data
          type: data
      podSpec:
        containers:
        - name: redis-sentinel
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 26379
              name: redis-sentinel
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /etc/conf
          command:
            - /bin/bash
          args:
            - -c
            - |
              set -e
              /scripts/redis-sentinel-start.sh
          lifecycle:
            postStart:
              exec:
                command: [ "/scripts/redis-sentinel-post-start.sh" ]
    - name: etcd
      workloadType: Stateful
      characterType: etcd
      probes:
      logconfigs:
      configSpecs:
      scriptsSpecs:
      podSpec:
        containers:
          - name: etcd
            imagePullPolicy: "IfNotPresent"
            securityContext:
              runAsNonRoot: true
              runAsUser: 1001
            livenessProbe:
              exec:
                command:
                  - /opt/bitnami/scripts/etcd/healthcheck.sh
              failureThreshold: 5
              initialDelaySeconds: 60
              periodSeconds: 30
              successThreshold: 1
              timeoutSeconds: 5
            readinessProbe:
              exec:
                command:
                  - /opt/bitnami/scripts/etcd/healthcheck.sh
              failureThreshold: 5
              initialDelaySeconds: 60
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 5
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /bitnami/etcd
                name: data
            dnsPolicy: ClusterFirst
            ports:
              - name: client
                containerPort: 2379
              - name: peer
                containerPort: 2380
            env:
              - name: BITNAMI_DEBUG
                value: "false"
              - name: MY_POD_IP
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: status.podIP
              - name: MY_POD_NAME
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
              - name: ETCDCTL_API
                value: "3"
              - name: ETCD_ON_K8S
                value: "yes"
              - name: ETCD_START_FROM_SNAPSHOT
                value: "no"
              - name: ETCD_DISASTER_RECOVERY
                value: "no"
              - name: ETCD_NAME
                value: $(MY_POD_NAME)
              - name: ETCD_DATA_DIR
                value: /bitnami/etcd/data
              - name: ETCD_LOG_LEVEL
                value: info
              - name: ALLOW_NONE_AUTHENTICATION
                value: "yes"
              - name: ETCD_ADVERTISE_CLIENT_URLS
                value: http://$(MY_POD_NAME).$(KB_CLUSTER_NAME)-etcd-headless.default.svc.cluster.local:2379
              - name: ETCD_LISTEN_CLIENT_URLS
                value: http://0.0.0.0:2379
              - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
                value: http://$(MY_POD_NAME).$(KB_CLUSTER_NAME)-etcd-headless.default.svc.cluster.local:2380
              - name: ETCD_LISTEN_PEER_URLS
                value: http://0.0.0.0:2380
              - name: ETCD_AUTO_COMPACTION_MODE
                value: revision
              - name: ETCD_AUTO_COMPACTION_RETENTION
                value: "1000"
              - name: ETCD_QUOTA_BACKEND_BYTES
                value: "4294967296"
              - name: ETCD_HEARTBEAT_INTERVAL
                value: "500"
              - name: ETCD_ELECTION_TIMEOUT
                value: "2500"
    - name: codis-proxy
      workloadType: Replication
      characterType: pika
      service:
        ports:
          - name: proxy
            targetPort: proxy
            port: 11080
          - name: admin
            targetPort: admin
            port: 19000
      configSpecs:
        - name: codis-proxy-config
          templateRef: pika-conf-template
          namespace: {{ .Release.Namespace }}
          volumeName: config
      volumeTypes:
        - name: data
          type: data
      podSpec:
        containers:
        - name: codis-proxy
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 11080
              name: proxy
            - containerPort: 19000
              name: admin
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /etc/conf
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ETCD_ADDR
              value: "pika-cluster-etcd-headless:2379"
            - name: DASHBOARD_ADDR
              value: "codis-dashboard:18080"
            - name: PRODUCT_NAME
              value: "codis-test"
          command:
            - "codis-proxy"
          args:
            - "-l"
            - "log/$(POD_NAME).log"
            - "-c"
            - "$(CODIS_PATH)/config/proxy.toml"
            - "--host-admin"
            - "$(POD_IP):11080"
            - "--host-proxy"
            - "$(POD_IP):19000"
            - "--etcd"
            - "$(ETCD_ADDR)"
            - "--product_name"
            - "$(PRODUCT_NAME)"
            - "--pidfile"
            - "log/proxy.pid"
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "codis-admin --dashboard=${DASHBOARD_ADDR} --remove-proxy --addr=${POD_IP}:11080 1>/dev/null 2>&1"
    - name: codis-ha
      workloadType: Stateful
      characterType: pika
      service:
        ports:
          - name: codis-ha
            targetPort: codis-ha
            port: 12345
      configSpecs:
        - name: codis-ha-config
          templateRef: pika-conf-template
          namespace: {{ .Release.Namespace }}
          volumeName: config
      volumeTypes:
        - name: data
          type: data
      podSpec:
        containers:
        - name: codis-ha
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 26379
              name: pika-sentinel
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /etc/conf
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DASHBOARD_ADDR
              value: "codis-dashboard:18080"
          command:
            - "/codis/bin/codis-ha"
          args: ["-l","log/$(POD_NAME).log","--interval","5","--dashboard=$(DASHBOARD_ADDR)"]
    - name: codis-fe
      workloadType: Stateless
      characterType: pika
      service:
        ports:
          - name: fe
            targetPort: fe
            port: 8080
      podSpec:
        containers:
        - name: codis-fe
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: fe
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ETCD_ADDR
              value: "pika-cluster-etcd-headless:2379"
          command:
            - "/codis/bin/codis-fe"
          args:
          - "-l"
          - "log/$(POD_NAME).log"
          - "--etcd"
          - "$(ETCD_ADDR)"
          - "--listen=$(POD_IP):8080"
          - "--assets=/codis/bin/assets"
    - name: codis-dashboard
      workloadType: Stateful
      characterType: pika
      service:
        ports:
          - name: dashboard
            targetPort: dashboard
            port: 18080
      configSpecs:
        - name: codis-dashboard-config
          templateRef: pika-conf-template
          namespace: {{ .Release.Namespace }}
          volumeName: config
      volumeTypes:
        - name: data
          type: data
      podSpec:
        containers:
        - name: codis-dashboard
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 18080
              name: dashboard
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /etc/conf
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ETCD_ADDR
              value: "pika-cluster-etcd-headless:2379"
            - name: PRODUCT_NAME
              value: "codis-test"
          command:
            - "/codis/bin/codis-dashboard"
          args:
            - "-l"
            - "log/$(POD_NAME).log"
            - "-c"
            - "$(CODIS_PATH)/config/dashboard.toml"
            - "--host-admin"
            - "$(POD_IP):18080"
            - "--etcd"
            - "$(ETCD_ADDR)"
            - "--product_name"
            - "$(PRODUCT_NAME)"
            - "--pidfile"
            - "log/dashboard.pid"
            - "--remove-lock"
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "/codis/bin/codis-admin --dashboard-list  --etcd=${ETCD_ADDR}"]
            preStop:
              exec:
                command: [/bin/sh", "-c", "PID=$(cat log/dashboard.pid) && kill $PID && while ps -p 1 > /dev/null; do sleep 1; done"]
