{
 "title": "Prometheus Pika Exporter",
 "tags": [
  "prometheus",
  "pika"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(pika_server_info, job)"
   },
   {
    "name": "group",
    "label": "Group",
    "query": "label_values(pika_server_info{job=~'$job'},group)"
   },
   {
    "name": "instance",
    "label": "Collect Instance",
    "query": "label_values(pika_server_info{job=~\"$job\", group=~'$group'}, instance)"
   },
   {
    "name": "addr",
    "label": "Pika Server Addr",
    "query": "label_values(pika_server_info{job=~\"$job\", group=~'$group'}, addr)"
   },
   {
    "name": "alias",
    "label": "Pika Server Alias",
    "query": "label_values(pika_server_info{job=~\"$job\", group=~'$group', addr=~'$addr'}, alias)"
   },
   {
    "name": "role",
    "label": "Role",
    "query": "label_values(pika_server_info{job=~\"$job\", group=~'$group', addr=~'$addr'}, role)"
   },
   {
    "name": "serverid",
    "label": "Server ID",
    "query": "label_values(pika_server_info{job=~\"$job\", group=~'$group', addr=~'$addr'}, server_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pika Build Info List",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "pika_build_info{job=~\"$job\", group=~\"$group\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Pika Server Info List",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "pika_server_info{job=~\"$job\", group=~\"$group\", instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Base Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Build Info",
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "pika_build_info{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
      }
     ]
    },
    {
     "title": "Server Info",
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "pika_server_info{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
      }
     ]
    },
    { "title": "Server ID", "type": "vonage-status-panel", "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 } },
    { "title": "Role", "type": "vonage-status-panel", "gridPos": { "h": 4, "w": 4, "x": 3, "y": 8 } },
    {
     "title": "Uptime",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 7, "y": 8 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "pika_uptime_in_seconds{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
      }
     ]
    },
    {
     "title": "Tread Num",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 10, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pika_thread_num{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
      }
     ]
    },
    {
     "title": "Sync Thread Num",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 13, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pika_sync_thread_num{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
      }
     ]
    },
    {
     "title": "Total Connections Received",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "pika_total_connections_received{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
      }
     ]
    },
    {
     "title": "Total Commands Processed",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "pika_total_commands_processed{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
      }
     ]
    },
    {
     "title": "Connected Clients",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pika_connected_clients{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "connected-clients"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(irate(pika_used_cpu_sys{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}[1m]) + irate(pika_used_cpu_user{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}[1m])) * 100",
       "legendFormat": "cpu-usage"
      }
     ]
    },
    {
     "title": "CPU Usage Children",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(irate(pika_used_cpu_sys_children{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}[1m]) + irate(pika_used_cpu_user_children{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}[1m])) * 100",
       "legendFormat": "cpu-usage-children"
      }
     ]
    },
    {
     "title": "Used Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pika_used_memory{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "used-memory"
      }
     ]
    },
    {
     "title": "DB Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pika_db_size{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "compression-{{compression}}"
      }
     ]
    },
    {
     "title": "DB Memtable Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pika_db_memtable_usage{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "db-memtable-usage"
      },
      {
       "expr": "pika_db_tablereader_usage{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "db-tablereader-usage"
      }
     ]
    },
    {
     "title": "Commands Processed in per second",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(pika_total_commands_processed{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}[5m])",
       "legendFormat": "commands-processed/sec"
      }
     ]
    },
    {
     "title": "The number of Keys",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pika_kv_keys{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "kv-keys"
      },
      {
       "expr": "pika_hash_keys{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "hash-keys"
      },
      {
       "expr": "pika_list_keys{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "list-keys"
      },
      {
       "expr": "pika_set_keys{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "set-keys"
      },
      {
       "expr": "pika_zset_keys{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "zset-keys"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    { "title": "Role", "type": "vonage-status-panel", "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 } },
    {
     "title": "Connected Slaves",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 4, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pika_master_info{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "connected-slaves"
      }
     ]
    },
    {
     "title": "Connected Slave List",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "pika_master_slave_info{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
      }
     ]
    },
    {
     "title": "Slave Info",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "pika_slave_info{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
      }
     ]
    },
    {
     "title": "Binlog Setting",
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "pika_binlog{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
      }
     ]
    },
    {
     "title": "Binlog Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pika_binlog{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "binlog size"
      }
     ]
    },
    {
     "title": "Binlog Offset",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pika_binlog_offset{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "file-num: [{{binlog_offset_filenum}}]  binlog-offset"
      }
     ]
    },
    {
     "title": "Double Master Info",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "pika_double_master_info{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
      }
     ]
    },
    {
     "title": "Double Master Binlog Offset",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pika_double_master_recv_info{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": "filenum:[{{double_master_recv_info_binlog_filenum}}]   binlog-offset"
      }
     ]
    }
   ]
  },
  {
   "title": "Time-consuming operation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scan Keyspace",
     "type": "table",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "pika_is_scaning_keyspace{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
      }
     ]
    },
    {
     "title": "Bgsave",
     "type": "table",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "pika_is_bgsaving{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
      }
     ]
    },
    {
     "title": "Slots Clean",
     "type": "table",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "pika_is_slots_cleaning{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
      }
     ]
    },
    {
     "title": "Slots Reload",
     "type": "table",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "pika_is_slots_reloading{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
      }
     ]
    },
    {
     "title": "Compact",
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "pika_is_compact{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Keys Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Key Size",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "pika_key_size{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}",
       "legendFormat": " {{key}} {{key_type}} {{db}} "
      }
     ]
    },
    {
     "title": "Key Value",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "pika_key_value{job=~\"$job\", group=~\"$group\", instance=~\"$instance\", addr=~\"$addr\", alias=~\"$alias\"}"
      }
     ]
    }
   ]
  }
 ]
}