
# libevent
FETCHCONTENT_DECLARE(
        libevent
        GIT_REPOSITORY https://github.com/libevent/libevent.git
        GIT_TAG release-2.1.12-stable
)

SET(EVENT__DISABLE_THREAD_SUPPORT ON CACHE BOOL "" FORCE)
SET(EVENT__DISABLE_OPENSSL ON CACHE BOOL "" FORCE)
SET(EVENT__DISABLE_BENCHMz`ARK ON CACHE BOOL "" FORCE)
SET(EVENT__DISABLE_TESTS ON CACHE BOOL "" FORCE)
SET(EVENT__DISABLE_REGRESS ON CACHE BOOL "" FORCE)
SET(EVENT__DISABLE_SAMPLES ON CACHE BOOL "" FORCE)
SET(EVENT__LIBRARY_TYPE STATIC CACHE STRING "" FORCE)
FETCHCONTENT_MAKEAVAILABLE(libevent)