# permissions for end users to edit pikas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pika-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pika-operator
    app.kubernetes.io/part-of: pika-operator
    app.kubernetes.io/managed-by: kustomize
  name: pika-editor-role
rules:
- apiGroups:
  - pika.openatom.org
  resources:
  - pikas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pika.openatom.org
  resources:
  - pikas/status
  verbs:
  - get
